### ISSUE TITLE
Getting issue while fetching the org. 

### ISSUE THREAD

**Issue by yasarshaikh** [bigassforce/metadata-backup#1]
Hi there,

Firstly, I would like to **thank you for the awesome tool**, which fetch the heavy metadata with step-by-step approach and using bulkRetrieve. 

I have got following issue, while fetching the Community. I would appreciate, if you Could assist me with this issue(in your free time, no hurries). 

> [antlib:com.salesforce:bulkRetrieve] Total number of items to be retrieved for Metadata type 'Community' = 5
> [antlib:com.salesforce:bulkRetrieve] Retrive Step 1. Retrieving following metadata objects: <<Removed_Name_of_community>> 

> [antlib:com.salesforce:bulkRetrieve] Request for a deploy submitted successfully.
> [antlib:com.salesforce:bulkRetrieve] Request ID for the current deploy task: <<removed_id>>
> [antlib:com.salesforce:bulkRetrieve] Waiting for server to finish processing the request...
> [antlib:com.salesforce:bulkRetrieve] Request Status: Failed

> BUILD FAILED
> D:\bckp_metadata\build.xml:14: The following error occurred while executing this line:
> D:\bckp_metadata\build.xml:74: Failed to process the request successfully. Cause(UNKNOWN_EXCEPTION): UNKNOWN_EXCEPTION: An unexpected error occurred. Please include this ErrorId if you contact support: 346144343-32864 (-768686627)

**Comment by bigassforce** [comment]
Escalated to Salesforce for further information -- Partner Case Number 22137425

**Comment by bigassforce** [comment]
Salesforce support follow up:

> Thank you for sharing the org id. I have checked the server logs. Please find the details.
> 
> =============
> 
> OrganizationId: << removed 00D org id >>
> UserId: << removed 005 user id >>
> **Subject: java.lang.RuntimeException: apex.parser.ApexParseException: unexpected token: s**
> 
> ============
> 
> Can you try following this article to make sure the entire process is using UTF-8 encoding? 
> 
> https://help.salesforce.com/apex/HTViewSolution?urlname=Use-UTF-8-Encoding-to-Deploy-Components-Whose-File-Names-Contain-Multibyte-Characters&language=en_US 
> 
> Regards, 
> << removed staff name >>
> Success Agent - Tier 2 
> Salesforce Technical Support 

---

> Description	
> UTF-8 encoding is required to deploy components whose file names contain multibyte characters. If UTF-8 is not the default encoding used in your Java environment for Metadata API or deployment tools, the deployment might fail. To ensure a successful deployment of these components, ensure that the UTF-8 encoding is used.
> Resolution	
> Depending on the tool you're using, specify the UTF-8 encoding by following one of these steps.
> 
> For Ant Migration Tool:
> Add -Dfile.encoding=UTF-8 to your ANT_OPTS environment variable. 
> 
> For Force.com IDE:
> Add the following line to eclipse.ini: -Dfile.encoding=UTF-8, and then restart Eclipse for this setting to take effect.

**Comment by bigassforce** [comment]
Fixed in 08df6b957d8b1a5f30ec5fe0ffc8dc087c680055
